version: '3.9'

volumes:
  keri-data:
  node-db:
  node-ipc:

services:
  cardano-backer:
    restart: unless-stopped
    build:
      context: .
      target: cardano-backer
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - keri-data:/usr/local/var/keri
    ports:
      - 5665:5665
      - 5666:5666 
  cardano-agent:
    restart: unless-stopped
    build:
      context: .
      target: cardano-agent
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - keri-data:/usr/local/var/keri
    ports:
      - 5971:5971
      - 5972:5972 
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:9.2.0
    command: [
      "run",
      "--config", "/config/config.json",
      "--database-path", "/data/db",
      "--socket-path", "/ipc/node.socket",
      "--topology", "/config/topology.json"
    ]
    volumes:
      - ./server/config/network/${NETWORK:-preprod}/cardano-node:/config
      - ./server/config/network/${NETWORK:-preprod}/genesis:/genesis
      - node-db:/data
      - node-ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
  ogmios:
    image: cardanosolutions/ogmios:latest
    restart: on-failure
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/cardano-node/config.json"
    ]
    volumes:
      - ./server/config/network/${NETWORK:-preprod}:/config
      - node-ipc:/ipc
    ports:
      - ${OGMIOS_PORT:-1337}:1337
