version: '3.9'

volumes:
  keri-data:

services:
  cardano-backer:
    restart: unless-stopped
    build:
      context: .
      target: cardano-backer
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - keri-data:/usr/local/var/keri
    ports:
      - 5665:5665
      - 5666:5666
