version: '3.9'

volumes:
  keri-data1:
  keri-data2:
  keri-data3:
  keri-data4:
  keri-data5:
  keri-data6:
  node-db:
  node-ipc:

services:
  cardano-backer-1:
    restart: unless-stopped
    build:
      context: .
      target: cardano-backer
    env_file: .env1
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - keri-data1:/usr/local/var/keri
    ports:
      - 5664:5664
      - 5674:5674
  cardano-backer-2:
    restart: unless-stopped
    build:
      context: .
      target: cardano-backer
    env_file: .env2
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - keri-data2:/usr/local/var/keri
    ports:
      - 5663:5663
      - 5673:5673
  cardano-backer-3:
    restart: unless-stopped
    build:
      context: .
      target: cardano-backer
    env_file: .env3
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - keri-data3:/usr/local/var/keri
    ports:
      - 5666:5666
      - 5676:5676
  cardano-backer-4:
    restart: unless-stopped
    build:
      context: .
      target: cardano-backer
    env_file: .env4
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - keri-data4:/usr/local/var/keri
    ports:
      - 5667:5667
      - 5677:5677
  cardano-backer-5: 
    restart: unless-stopped
    build:
      context: .
      target: cardano-backer
    env_file: .env5
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - keri-data5:/usr/local/var/keri
    ports:
      - 5668:5668
      - 5678:5678
  cardano-backer-6: 
    restart: unless-stopped
    build:
      context: .
      target: cardano-backer
    env_file: .env6
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - keri-data6:/usr/local/var/keri
    ports:
      - 5669:5669
      - 5679:5679
  cardano-node:
    image: ghcr.io/blinklabs-io/cardano-node:10.4.1-2
    environment:
      - NETWORK=${NETWORK:-preview}
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-false}
    volumes:
      - node-db:/data
      - node-ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
  ogmios:
    image: cardanosolutions/ogmios:v6.12.0
    restart: on-failure
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/${NETWORK:-preview}/cardano-node/config.json"
    ]
    environment:
      - NETWORK=${NETWORK:-preview}
    volumes:
      - node-ipc:/ipc
    ports:
      - ${OGMIOS_PORT:-1337}:1337